name: visualpython-binder
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - pip
  - pip:
    - seaborn
    - scikit-learn
    - jupyterlab-visualpython==2.4.0
